project:
  type: website
  output-dir: _site

filters:
  - webr

website:
  title: "Botany ENM Workshops"

  sidebar:
    style: docked
    search: true
    contents:
      - index.qmd
      - 00_Setup.qmd
      - 01_Data_Downloads.qmd
      - 02_Data_Cleaning.qmd
      - 03_Data_Exploration.qmd
      - 04_AccessibleArea_VariableSelection.qmd
      - 05_Ecological_Niche_Modeling.qmd
      - 06_Null_ENMs.qmd
      - 07_ENM_Processing.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true
    code-fold: false
