project:
  type: book
  output-dir: _book

book:
  title: "Botany 2026 ENM Workshop"
  chapters:
    - index.qmd
    - chapters/00_Setup.qmd
    - chapters/01_Data_Downloads.qmd
    - chapters/02_Data_Cleaning.qmd
    - chapters/03_Data_Exploration.qmd
    - chapters/04_AccessibleArea_VariableSelection.qmd
    - chapters/05_Ecological_Niche_Modeling.qmd
    - chapters/06_Null_ENMs.qmd
    - chapters/07_ENM_Processing.qmd
    - chapters/08_Phylodiversity_Phyloendemism.qmd

format:
  html:
    theme: cosmo
    code-fold: false
    code-tools: true

filters:
  - webr

webr:
  packages: ['leaflet']  # Start empty, add packages as needed
  show-startup-message: false
  show-header-message: false
